import streamlit as st
import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "../..")))

from frontend.utils.auth_state import require_login, get_token
from frontend.utils import api_client as api

st.set_page_config(page_title="AI Recommendations", page_icon="💡", layout="wide")
require_login()
token = get_token()

st.markdown("""<style>
    .rec-card { border-radius:12px; padding:16px 20px; margin:10px 0; }
    .rec-feeding    { background:#f1f8e9; border-left:4px solid #2e7d32; }
    .rec-medication { background:#fff3e0; border-left:4px solid #e65100; }
    .rec-preventive { background:#e3f2fd; border-left:4px solid #1565c0; }
    .rec-general    { background:#f3e5f5; border-left:4px solid #6a1b9a; }
    
    [data-testid="stSidebar"] { background:linear-gradient(180deg,#14532d,#166534,#15803d); }
    [data-testid="stSidebar"] * { color:white !important; }
    [data-testid="stSidebar"] hr { border-color:rgba(255,255,255,0.15); }
    @import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;600;700;800&display=swap');
    html, body, [class*="css"] { font-family: 'Inter', sans-serif; }
    #MainMenu{visibility:hidden} footer{visibility:hidden}
</style>""", unsafe_allow_html=True)

st.markdown("""
<div style='background:linear-gradient(135deg,#14532d,#16a34a);
     border-radius:16px; padding:24px 28px; margin-bottom:24px; color:white;
     display:flex; align-items:center; justify-content:space-between;'>
    <div>
        <h2 style='margin:0; font-size:1.6rem; font-weight:800;'>💡 AI Recommendations</h2>
        <p style='margin:6px 0 0; opacity:0.85; font-size:0.92rem;'>Personalized feeding, medication and preventive care plans generated by Groq LLM</p>
    </div>
    <div style='font-size:3rem; opacity:0.3;'>💡</div>
</div>
""", unsafe_allow_html=True)

cows_res = api.get_cows(token)
if cows_res.status_code != 200 or not cows_res.json():
    st.warning("No cows registered. Please add cows first.")
    st.stop()

cows     = cows_res.json()
cow_opts = {f"{c['name']} ({c['cow_uid']})": c["id"] for c in cows}

tab1, tab2, tab3 = st.tabs(["  Get Recommendations  ", "  Deep AI Analysis  ", "  History  "])

icons = {"feeding": "🌾", "medication": "💊", "preventive": "🛡️", "general": "📌"}
colors = {"feeding": "rec-feeding", "medication": "rec-medication",
          "preventive": "rec-preventive", "general": "rec-general"}

with tab1:
    st.markdown("#### Select a Cow")
    selected = st.selectbox("Cow", list(cow_opts.keys()), label_visibility="collapsed")
    cow_id   = cow_opts[selected]
    st.markdown("<div style='color:#666;font-size:0.9rem;margin:8px 0 16px'>AI will analyze the latest health & milk data for this cow and generate 3 personalized recommendations.</div>", unsafe_allow_html=True)

    if st.button("Generate Recommendations", type="primary", use_container_width=True):
        with st.spinner("AI is analyzing cow data..."):
            res = api.generate_recommendations(token, cow_id)
        if res.status_code == 200:
            recs = res.json()
            st.success(f"{len(recs)} recommendations generated!")
            for rec in recs:
                rtype = rec["rec_type"]
                icon  = icons.get(rtype, "📌")
                css   = colors.get(rtype, "rec-general")
                st.markdown(f"""<div class='rec-card {css}'>
                    <div style='font-weight:700;font-size:1rem;margin-bottom:6px'>{icon} {rtype.upper()}</div>
                    <div style='color:#333;line-height:1.6'>{rec['content']}</div>
                </div>""", unsafe_allow_html=True)
        else:
            st.error(res.json().get("detail", "Failed to generate recommendations."))

with tab2:
    st.markdown("#### Deep AI Analysis")
    st.markdown("<div style='color:#666;font-size:0.9rem;margin-bottom:16px'>Comprehensive analysis using Llama 3.3 70B — reviews health trends, milk patterns, and creates a 30-day action plan.</div>", unsafe_allow_html=True)
    sel2 = st.selectbox("Cow", list(cow_opts.keys()), key="ag_cow", label_visibility="collapsed")
    cid2 = cow_opts[sel2]

    if st.button("Run Deep Analysis", type="primary", use_container_width=True):
        with st.spinner("Deep AI analysis in progress... (may take 15-20 seconds)"):
            res = api.agentic_analyze(token, cid2)
        if res.status_code == 200:
            data = res.json()
            st.success(f"Analysis complete for **{data['cow_name']}**")
            st.markdown(f"""
            <div style='background:white;border-radius:14px;padding:20px;
                border:1px solid #e8f5e9;line-height:1.8;color:#333'>
                {data['insights'].replace(chr(10), '<br>')}
            </div>""", unsafe_allow_html=True)
            st.caption(f"Powered by {data['model_used']}")
        else:
            st.error("Analysis failed. Please try again.")

with tab3:
    st.markdown("#### Recommendation History")
    sel3 = st.selectbox("Cow", list(cow_opts.keys()), key="rec_hist", label_visibility="collapsed")
    cid3 = cow_opts[sel3]
    hr   = api.get_recommendations(token, cid3)

    if hr.status_code == 200:
        recs = hr.json()
        if not recs:
            st.info("No recommendations yet. Generate some from the first tab.")
        else:
            st.markdown(f"<div style='color:#666;margin-bottom:12px'><b>{len(recs)}</b> recommendation(s) found</div>", unsafe_allow_html=True)
            for rec in recs:
                rtype = rec["rec_type"]
                icon  = icons.get(rtype, "📌")
                css   = colors.get(rtype, "rec-general")
                with st.expander(f"{icon} {rtype.upper()} — {rec['created_at'][:10]}"):
                    st.markdown(f"<div style='line-height:1.7;color:#333'>{rec['content']}</div>", unsafe_allow_html=True)
